{% set version = "0.1.6" %}

package:
  name: gopeaks
  version: {{ version }}

source:
  url: https://github.com/maxsonBraunLab/gopeaks/archive/refs/tags/v{{ version }}.tar.gz

build:
  script: |
    mkdir -p ${PREFIX}/bin
    GOOS=linux GOARCH=amd64 go build -o ${PREFIX}/bin

requirements:
  build:
    - gxx_linux-64
    - go=1.15.11

about:
  home: https://github.com/maxsonBraunLab/gopeaks
  summary: 'CUT&TAG peak caller'
  description: |
    Gopeaks calls peaks on CUT&TAG sequencing data.  
  dev_url: https://github.com/maxsonBraunLab/gopeaks 
