{% set version = "0.1.7" %}

package:
    name: gopeaks
    version: {{ version }}

source:
    url: https://github.com/maxsonBraunLab/gopeaks/releases/download/v{{ version }}/gopeaks-linux-amd64

build:
    binary_relocation: false

test: 
   commands: 
       - gopeaks -h

about:
    home: https://github.com/maxsonBraunLab/gopeaks
    license: MIT
    summary: 'CUT&TAG peak caller'

extra: 
    - should_be_noarch_generic
    - should_not_be_noarch_source
