{% set version = "0.1.7" %}

package:
  name: gopeaks
  version: {{ version }}

source:
   - url: https://github.com/maxsonBraunLab/gopeaks/archive/refs/tags/v{{ version }}.tar.gz
     sha256: 85d98aea13617a211e82465629427904e42635973fd23540a309601ce15955da

build:
  number: 0
  binary_relocation: false      
      
test: 
  commands: 
     - gopeaks -h

about:
  home: https://github.com/maxsonBraunLab/gopeaks
  license: MIT
  summary: 'CUT&TAG peak caller'

extra: 
  skip-lints:
    - should_be_noarch_generic
    - should_not_be_noarch_source
