name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    
    - name: Set up Go 1.5
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Tidy Dependencies
      run: |
        go mod tidy
    - name: Build
      run: go build -v .

    - name: Test
      run: go test -v
